name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # O la rama que quieras usar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # O la versión que estés usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tu-nombre-de-app'  # Reemplaza con el nombre de tu aplicación en Azure
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Necesitas agregar este secreto
